### ISSUE TITLE
Can't find keyplane that supports type 5 for keyboard

### ISSUE THREAD

**Issue by brnardo** [driftyco/ionic-plugins-keyboard#73] opened 2015-03-16 18:38 UTC
Hi,

I'm using a numeric keyboard for a specific input the first time I tap to use it, it takes a lot of time to show up. Meanwhile the console spits out:

Can't find keyplane that supports type 5 for keyboard iPhone-Portrait-NumberPad; using 3876877096_Portrait_iPhone-Simple-Pad_Default

I've updated Ionic Keyboard to 1.0.4 and still get the error.

**Comment by tlancina** [comment] 2015-03-16 23:34
Duplicate of: https://github.com/driftyco/ionic-plugins-keyboard/issues/48.

**Closed by tlancina** 2015-03-16 23:34 UTC
