### ISSUE TITLE
Closing of keyboard unexpectedly

### ISSUE THREAD

**Issue by ABHIJEET-MUNESHWAR** [driftyco/ionic-plugins-keyboard#65] opened 2015-02-10 09:56 UTC
Hi,

Keyboard is closing unexpectedly on typing of first character in Android 4.0.4

Please help me.

**Comment by tlancina** [comment] 2015-03-09 21:16
Hey I'm going to close this for now as I'm unable to reproduce it.  Feel free to post some code that reproduces the issue and re-open.

**Closed by tlancina** 2015-03-09 21:16 UTC
