### ISSUE TITLE
whole view flicker when keyboard show/hide

### ISSUE THREAD

**Issue by mydearxym** [driftyco/ionic-plugins-keyboard#64] opened 2015-02-08 01:54 UTC
test on my android device, my config.xml is like this, i tried some combination but not work 
any hint?
```xml
<preference name="webviewbounce" value="false" />
<preference name="UIWebViewBounce" value="false" />
<preference name="DisallowOverscroll" value="true" />
<preference name="HideKeyboardFormAccessoryBar" value="false"/>
<preference name="KeyboardShrinksView" value="true" />
<preference name="Orientation" value="portrait" />
<preference name="hardwareAccelerated" value="false" />
<preference name="DisableScrollingWhenKeyboardShrinksView" value="true" />
<preference name="EnableViewportScale" value="false" />
<preference name="KeyboardDisplayRequiresUserAction" value="false" />
```

**Comment by tlancina** [comment] 2015-02-09 18:11
Hmm not sure, what version of android and what device type?

**Comment by softBarbarian** [comment] 2015-02-09 18:14
I am seeing same thing on iOS too...
Whole ionic app 'jumps' up and down when keyboard is opening. Will try to record a video

**Comment by softBarbarian** [comment] 2015-02-09 18:25
Ok, I got more info. 
When an input field is below the line where the keyboard will be when opened, the app scrolls the input to the visible area but before it does it jitters whole view.

**Comment by tlancina** [comment] 2015-02-09 22:59
@softBarbarian sounds like you're having a different issue, that is expected behavior if you don't have `disableScroll(true)`.

**Comment by tlancina** [comment] 2015-02-09 23:06
Ah actually maybe it is the same thing, sorry, by flicker I was thinking a visible flash.  @mydearxym if by flicker you mean what @softBarbarian described then what is most likely happening is the webview _and_ Ionic are trying to scroll the inputs into view (assuming you're using Ionic).  You can try messing with the viewport meta tag or following some of the config options at http://ionicframework.com/docs/api/page/keyboard/ to see if those help.

**Comment by tlancina** [comment] 2015-03-04 20:09
Closing this for now, might be similar to https://github.com/driftyco/ionic/issues/1791.

Also noticing a black flash on Lollipop when the keyboard opens even without the keyboard plugin installed.

**Closed by tlancina** 2015-03-04 20:09 UTC

**Comment by softBarbarian** [comment] 2015-03-05 01:16
I was able to fix it today by adding Keyboard.disableScroll(true) to my platform.ready block

**Comment by brethren70** [comment] 2015-07-20 14:11
I have same issue with only using crosswalk.

**Comment by adamduren** [comment] 2015-08-02 16:16
I am seeing the black flash on Lollipop as well the whole app jumping as the keyboard opens. It seems odd because I only have two inputs in the view and they are definitely in view and would not be obscured by the keyboard.

**Comment by adamduren** [comment] 2015-08-02 17:00
I fixed the app jumping, it turned out to be crosswalk and was fixed by modifying `XWalkCordovaView.java` file. Still working on the black flash bug.

**Comment by adsahay** [comment] 2015-08-07 13:29
@adamduren can you share this fix?

**Comment by adamduren** [comment] 2015-08-08 19:28
Sure and sorry for the slow response, 

My original fix involved adding this line to the `setGlobalPref` function in `plugins/cordova-plugin-crosswalk-webview/platforms/android/src/org/crosswalk/XWalkCordovaView.java`
```java
XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, false);
```

I didn't like this as is was not source controlled. I found that they are fixing this issue in the next release of `cordova-plugin-crosswalk-webview`. It just has not been released yet. If you want you can install the latest cordova version `npm install -g cordova@5.2.0` and then install the master of the crosswalk plugin with `ionic plugin add https://github.com/crosswalk-project/cordova-plugin-crosswal k-webview.git#master`.

Hopefully they will release this soon so the workaround is not needed.

**Comment by adsahay** [comment] 2015-08-10 09:51
@adamduren incredibly helpful, thanks! I'm thinking of keeping changes local and writing a `before_prepare` hook to patch the contents.

**Comment by adamduren** [comment] 2015-08-10 15:32
@adsahay Sounds like a good idea. It was definitely a frustrating issue, glad I could help. :smile:

**Comment by resolverRaun** [comment] 2015-08-27 12:16
XWalkPreferences.setValue(XWalkPreferences.ANIMATABLE_XWALK_VIEW, false);
By editing this line in  XWalkCordovaView.java file  didnot resolve my problem. The screen still flicker when keyboard shows and hide.

**Comment by baleboy** [comment] 2015-08-27 13:09
Crosswalk 15 has additional fixes that may help. Unfortunately however it doesn't work with the plugin released to NPM - we are planning to update it soon, but meanwhile you would have to use the latest plugin master from github and add the preference <preference name="xwalkVersion" value="xwalk_core_library_beta:15+" /> to your config.xml

**Comment by kamaljit-sharma** [comment] 2016-10-16 22:09
i was facing the same issue, after lot of digging i got the solution :)
set android:windowSoftInputMode="adjustPan" in activity tag of your android manifest file

This worked for me

**Comment by johnnynode** [comment] 2016-12-05 01:46
@kamaljit-sharma , the view should push up automatically , if set it as "adjustPan" or "adjustPan|stateHidden" , keyboard may cover input areas , It's not a good solution.

**Comment by johnnynode** [comment] 2016-12-05 05:08
Try this:
1. set android:windowSoftInputMode="adjustPan" 
2. set css code like this:
>.keyboard-up{
>    transition: all .2s ease 0s;
>    -webkit-transition: all .2s ease 0s;
>    transform: translateY(-20%);
>    -webkit-transform: translateY(-20%);
>}
3. then for the ion-content directive :
> <ion-content ng-class="{'keyboard-up':kbUp}">
4. in your controller:
>(function(){
>    window.addEventListener('native.keyboardshow', function () {
>        $scope.kbUp = true;
>    });
>
>   window.addEventListener('native.keyboardhide', function () {
>       $scope.kbUp = false;
>   });
>})();
It's works fine for me!

**Comment by RicardoBer** [comment] 2017-02-10 00:55
I think this is the worst problem I see on ionic, And application has two vital things, User input, an output after some operations.

this problem makes ionic inusable for me.

At this moment I can't find a correct solution, but this not occurs on ios.

I take johnnynode solution, but I see one problem, 20% is an arbitary value, and don't works on large forms.

In the controller put this code (not in all, only in large forms).

```
  (function(){
   window.addEventListener('native.keyboardshow', function (e) {
     angular.element(document.querySelector('ion-content')).css('margin-bottom',+e.keyboardHeight+'px');
     $scope.$apply();
   });

  window.addEventListener('native.keyboardhide', function (e) {
     angular.element(document.querySelector("ion-content")).css('margin-bottom','0px');
     $scope.$apply();
   }); 
  })();
```
I think to put this on app.js, after ckecking keyboard plugin is present, but if you has a background image it left a terrible white rectangle for milliseconds when keyboard is hiden
